version: '3'
services:
  backend:
    build: 
      context: ./backend
    volumes:
      - ./backend:/app 
    ports: 
      - "4000:4000"
    environment:
      - NODE_ENV=production

  frontend:
    build: 
      context: .
    volumes: 
      - .:/app
    ports: 
      - "80:3000"
    environment:
      - NODE_ENV=production
    depends_on: 
      - backend
