version: '3'
services:
  backend:
    build: 
      context: ./backend
    volumes:
      - ./backend:/app 
    ports: 
      - "4000:4000"
    environment:
      - NODE_ENV=development

  frontend:
    build: 
      context: .
    volumes: 
      - .:/app
    ports: 
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on: 
      - backend
