version: '3'
services:
  frontend:
      image: vintvgx/urban-ai-client:latest
      restart: unless-stopped
      ports: 
        - "3000:3000"
        - "443:443"
      environment:
        - NODE_ENV=production
      depends_on: 
        - backend
  backend:
    image: vintvgx/urban-ai-server:latest
    restart: unless-stopped
    ports: 
      - "4000:4000"
    environment:
      - NODE_ENV=production

#* local setup
# version: '3'
# services:
#   backend:
#     build: 
#       context: ./backend
#     volumes:
#       - ./backend:/app 
#     ports: 
#       - "4000:4000"
#     environment:
#       - NODE_ENV=production

#   frontend:
#     build: 
#       context: .
#     volumes: 
#       - .:/app
#     ports: 
#       - "80:3000"
#     environment:
#       - NODE_ENV=production
#     depends_on: 
#       - backend
